post 관련 backend customizing
osamhack2021/AI_WEB_POOL_YD pull request #28
Opened 2021-10-14 03:30 UTC by Ever2after

- /posts/full(/:id), /posts/preview(/:id) get method 추가
 - /posts/discover post method 추가
 - db 구조 다수 변경 (notion 참조)

2021-10-14 13:27 UTC, somnisomni requested changes

2021-10-14 13:27 UTC, somnisomni commented on Web/vue.config.js
> +>>>>>>> a25a140e740bd1ec391f327a12774e397e23ba71
핵폭탄 발견...! :bomb: 이거.... 머지하다가 만게 남아있네요.

2021-10-14 13:27 UTC, somnisomni commented on Backend/.env
> +DATABASE_URI = mongodb+srv://pooluser:pool1234@poolcluster.mnjek.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
`.env`는 보통 리포지토리에는 올라오면 안되는 데이터들이 포함되는 경우가 많아서 `.gitignore`에 등록해두곤 해요. `DATABASE_URI`도 그런 것 같은데... 혹시 편의상 올려두신건가 싶어서 질문해요! 악의를 가진 사람이 이거 보고 뭘 할지 모르는거라...

보통은 데이터가 들어간 `.env`는 리포지토리에 올리지 않고 팀원끼리 서로 private하게 공유하는 것 같더라구요.

2021-10-14 13:33 UTC, Ever2after commented on Web/vue.config.js
> +>>>>>>> a25a140e740bd1ec391f327a12774e397e23ba71
이거 때문에 draft로 바꾼겁니다 ㅋㅋ....

2021-10-14 13:33 UTC, somnisomni commented on Web/vue.config.js
> +>>>>>>> a25a140e740bd1ec391f327a12774e397e23ba71
아....아앗...

2021-10-14 13:34 UTC, Ever2after commented on Backend/.env
> +DATABASE_URI = mongodb+srv://pooluser:pool1234@poolcluster.mnjek.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
귀찮아서 그냥 gitignore에서 뺐는데 아무래도 그게 맞겠죠? 세상 일이 어찌될지 모르니...

2021-10-14 13:35 UTC, somnisomni commented on Backend/.env
> +DATABASE_URI = mongodb+srv://pooluser:pool1234@poolcluster.mnjek.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
전 잘 모르겠지만 리포에 이런거 남아있으면 감점요소가 될 수 있을지 모르겠네용...

2021-10-14 14:35 UTC, wooksong commented on Backend/.env
> +DATABASE_URI = mongodb+srv://pooluser:pool1234@poolcluster.mnjek.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
ssh-key라든지, 저런 db 계정이라든지가 github에 노출되면 큰일이죠;

2021-10-14 14:41 UTC, wooksong commented on Backend/.env
> +DATABASE_URI = mongodb+srv://pooluser:pool1234@poolcluster.mnjek.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
0. Encryption/Decryption을 적용하는 것도 방법인데, 배보다 배꼽이 더 커질 수 있겠네요. 
1. [git-secret](https://kimmj.github.io/git/git-secret/)으로 해당 파일 자체를 공유는 하되, GPG key로 암호화 할 수 있습니다. GPG key를 생성한다고 해도, key-server에 등록하고 등등 이것도 시간이 걸릴 수 있구요.
2. Github Actions + Docker로 deploy 하실 예정이면 [Github.secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) 이용하셔도 됩니다.
3. 이도 저도 귀찮으면 모든 팀원이 ```export DATABASE_USER``` ```export DATABASE_PASSWORD```를 하고 있다는 가정하에 동작하도록 프로그래밍하셔도 되구요.

2021-10-15 13:18 UTC, somnisomni submitted a review, later dismissed

2021-10-16 06:00 UTC, woosukji approved these changes

2021-10-16 06:00 UTC, merged